image: docker:19.03.1

services:
  - docker:19.03.1-dind

stages:
  - build
  - test

build:
  stage: build
  script:
    - apk add bash
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - bash build.sh

test:
  stage: test
  before_script:
    - docker info
    - apk add --update py3-pip
    - pip3 install docker-compose
  script:
    - docker-compose up --exit-code test
    - docker-compose up --exit-code test_prescript
    - docker-compose up --exit-code test_fail && echo "This should fail !" && exit 1
