image: tmaier/docker-compose:20.10

services:
  - docker:dind

stages:
  - build
  - test

build:
  stage: build
  only:
    - master
  script:
    - apk add bash
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - bash build.sh

test:
  stage: test
  script:
    - docker-compose up --exit-code test test
    - docker-compose up --exit-code test_prescript test_prescript
    - docker-compose up --exit-code test_fail test_fail && exit 1 || echo "this fail as if should be"
