version: "3"

services:
  test:
    image: henri9813/golang-test
    working_dir: /project
    volumes:
      - ./project:/project
  test_prescript:
    image: henri9813/golang-test
    working_dir: /project_withprescript
    volumes:
      - ./project_withprescript:/project_withprescript
    environment:
      BEFORE_RUN: "make"
