version: "3"

services:
  golang-test:
    build: .
    image: henri9813/golang-test
  test:
    image: henri9813/golang-test
    working_dir: /project
    volumes:
      - ./project:/project
  test_prescript:
    image: henri9813/golang-test
    working_dir: /project_withprescript
    volumes:
      - ./project_withprescript:/project_withprescript
    environment:
      BEFORE_RUN: "make"
  test_nogomod:
    image: henri9813/golang-test
    working_dir: /project_nogomod
    volumes:
      - ./project_nogomod:/project_nogomod
    environment:
      SINGLE_PACKAGE: "true"
  test_fail:
    image: henri9813/golang-test
    working_dir: /project_fail
    volumes:
      - ./project_fail:/project_fail
  test_exclude_packages:
    image: henri9813/golang-test
    working_dir: /project_except_some_packages
    volumes:
      - ./project_except_some_packages:/project_except_some_packages
    environment:
      EXCLUDED_PACKAGES: "addition"
  test_majorversion:
    image: henri9813/golang-test
    working_dir: /project_withmajorversion
    volumes:
      - ./project_withmajorversion:/project_withmajorversion
